---
- hosts:        all
  gather_facts: no
  sudo:         yes

  tasks:
    - name: add ssh keys
      authorized_key:
        user: vagrant
        key:  "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    - name: update ubuntu
      apt:  update_cache=yes

    - name: instal curl package
      apt:  name=curl state=present

    - name: install squid
      apt:  name=squid3 state=present

    - include: tasks/copy_config_file.yml
      notify:  start squid

    - name: copy aliases
      copy: src=files/.bash_aliases dest=/home/vagrant/.bash_aliases

  handlers:
    - name: start squid
      service:
        name:  squid3
        state: started
