---
- include: squid.yml
  vars:
    host:            squid1
    proxy_ip:        '192.168.56.101'
    line_proxy_path: 'cache_peer 192.168.56.102 sibling 3128 3130 default'
    hierarchy_name:  'hierarchy4-squid1'

- include: squid.yml
  vars:
    host:            squid2
    proxy_ip:        '192.168.56.102'
    line_proxy_path: 'cache_peer 192.168.56.101 sibling 3128 3130 default'
    hierarchy_name:  'hierarchy4-squid2'

- include: squid.yml
  vars:
    host:            squid3
    proxy_ip:        '192.168.56.103'
    line_proxy_path: 'cache_peer 192.168.56.102 parent 3128 3130 default'
    hierarchy_name:  'hierarchy4-squid3'
