---
- hosts:        '{{ host }}'
  gather_facts: no
  sudo:         yes
  tasks:
    - include: ../tasks/copy_config_file.yml
    - include: ../tasks/insert_proxy_path.yml
    - include: ../tasks/reload_squid.yml
    - include: ../tasks/clear_cache_and_logs.yml
    - include: ../tasks/make_curl_request.yml
    - include: ../tasks/make_curl_request.yml
    - include: ../tasks/fetch_access_logs.yml
